### PR TITLE
fix for int.pow zero raised to negative power

### LINKED ISSUE #193: [bug] wrong int.pow implementation
### Problem
The `int.pow` attribute object implementation is wrong.  
For all `b < 0`, `0^b` should be undefined. For now, it is a large `int` number that corresponds to `(long) Double.POSITIVE_INFINITY` (`9223372036854775807`). This may be ok for `FPU` computations to return `+∞`. However, for integer computations returning `9223372036854775807` seems ambiguous. 
### Example  
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%d\n%d\n%d\n%d\n%d\n"
      0.pow 0
      0.pow -1
      0.pow -2
      0.pow -1000
      0.pow 1

```
#### Running
```
IN$: ./run.sh
OUT>: 1
OUT>: 9223372036854775807
OUT>: 9223372036854775807
OUT>: 9223372036854775807
OUT>: 0
IN$: 
```
#### Comment
`0^1 = 1` is correct  
`0^0 = 1` is okay, even though the opinions vary on this point ([link](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero)). 
`0^(-1), 0^(-2), 0^(-1000)` should be either `unfedined`, `+∞`, `zero division exception`, not `9223372036854775807`.

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #193

### CODE REVIEW

**Comment by nlchar** [comment]
@yegor256 how do we raise exceptions inside EO-Runtime Java Code?  
I wanted to raise ArithmeticException at first, but it doesn't work properly, because the exception is thrown inside a lambda. Raising the exception outside the lambda code does not comply with the principles the EO Runtime works (i.e. the runtime bases on the lazy evaluation principle, while here we would face the eager evaluation example).
I also tried to return something like this instead of an exception inside lambda:
```
[]
  "0 cannot be raised to a negative power" > message
```
However, I failed at coding the upper exception-object inside Java, because I do not understand how to add a new attribute (PhDefault.add is protected. No other Ph* objects contain the `add` method). 
Please, leave short guidance on how to raise exceptional cases in the eo-runtime code properly.

**Comment by yegor256** [comment]
@nlchar I suggest we create a new object `error` (similar to `int` and `string` we already have) and just return a copy of it:

```
[msg] > error
```

**Comment by nlchar** [comment]
@yegor256 ready for review

File: eo-runtime/src/test/java/org/eolang/EOintEOpowTest.java [hunk 1]
```diff
@@ -51,4 +53,59 @@ public void powersNumber() {
         );
     }
 
+    @Test
+    public void zeroNonNegativePowers() {
+        // 0^0
+        MatcherAssert.assertThat(
```
Comment (yegor256) [inline eo-runtime/src/test/java/org/eolang/EOintEOpowTest.java:59]: @nlchar it's better to have one assertion per test: https://softwareengineering.stackexchange.com/questions/7823/is-it-ok-to-have-multiple-asserts-in-a-single-unit-test

Comment (nlchar) [reply eo-runtime/src/test/java/org/eolang/EOintEOpowTest.java:58]: @yegor256 thank you. Fixed that. I kept two asserts in `zeroToNegativePowerFails`, though. Because those test that:
1. The `error` object is returned and the object has the proper `msg` value.
2. The code does not datarize, so it would fail in real-life code, which is our goal. 

The QA you attached accepts this. I can change it if you like.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#203` is not assigned, can't get performer
